import type { FerretReviewer } from '@errorferret/reviewers';



export type FileSubmission = {
  name: string;
  language: string;
  code: string;
}

/**
 * Defines the ways to configure the prompt, changing the type of feedback generated by the LLM
 */
export type PromptConfig = {
  files: FileSubmission[];
  reviewers: FerretReviewer[];
}


/**
 * Defines the structure of the response from the LLM (as described in the system prompt)
 */
export interface LLMResponseItem {
  file: FileSubmission;
  line: string;
  lineNumber: number;
  reviewer: FerretReviewer;
  feedback: string;
}

/**
 * Defines a single feedback item, parsed from the LLM response
 */
export interface FeedbackItem {
  lineNum: number;
  columnNum: number;
  code: string;
  contextLines: CodeReference[];
  feedback: string;
}

/**
 * Defines the structure of the response from the feedback service
 */
export interface FeedbackResponse {
  feedbackItems: FeedbackItem[];
  language: string;
  focus: string;
  timestamp: string;
}


/**
 * Defines a reference to a line of user code, used to display the context of the feedback
 */
export interface CodeReference {
  lineNum: number;
  code: string;
}