name = "error-ferret"
main = "dist/worker/entry.js"
compatibility_date = "2024-01-01"

# Remove SESSION binding to avoid warnings
[build]
command = "npm run build"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

# Environment variables for OpenAI API
# These will be set in the Cloudflare dashboard or via wrangler secret
# wrangler secret put OPENAI_API_KEY
