apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: error-ferret
spec:
  replicas: 1
  selector: { matchLabels: { app: api } }
  template:
    metadata: { labels: { app: api } }
    spec:
      containers:
        - name: api
          image: ghcr.io/robinsr/error-ferret-api:{{TAG}}
          ports: [{ containerPort: 3000 }]
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            - name: NATS_URL
              valueFrom:
                configMapKeyRef: { name: api-config, key: NATS_URL }
          envFrom:
            - secretRef: { name: openai-secret }   # contains OPENAI_API_KEY
          resources:
            requests: { cpu: "50m", memory: "128Mi" }
            limits:   { cpu: "200m", memory: "256Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: error-ferret
spec:
  selector: { app: api }
  ports:
    - name: http
      port: 80
      targetPort: 3000