apiVersion: v1
kind: Service
metadata:
  name: nats-monitoring
  namespace: error-ferret
  labels:
    app.kubernetes.io/name: nats
spec:
  selector:
    app.kubernetes.io/name: nats
  ports:
    - name: monitoring
      port: 8222
      targetPort: 8222