
/**
 * Defines the experience levels of the user
 */
export const EXPERIENCE_LEVELS = ['novice', 'apprentice', 'experienced', 'professional', 'expert'] as const;
export type ExperienceLevel = (typeof EXPERIENCE_LEVELS)[number];

/**
 * Defines the focus areas of the feedback
 */
export const FOCUS_AREAS = ['general', 'performance', 'maintainability', 'clarity', 'idiomatic_usage', 'security'] as const;
export type FocusArea = (typeof FOCUS_AREAS)[number];


/**
 * Defines the ways to configure the prompt, changing the type of feedback generated by the LLM
 */
export interface PromptConfig {
  language: string;
  focus: FocusArea;
  experienceLevel: ExperienceLevel;
}


/**
 * Defines the structure of the response from the LLM (as described in the system prompt)
 */
export interface LLMResponseItem {
  line: string;
  lineNumber: number;
  feedback: string;
}

/**
 * Defines a single feedback item, parsed from the LLM response
 */
export interface FeedbackItem {
  lineNum: number;
  columnNum: number;
  code: string;
  contextLines: CodeReference[];
  feedback: string;
}

/**
 * Defines the structure of the response from the feedback service
 */
export interface FeedbackResponse {
  feedbackItems: FeedbackItem[];
  language: string;
  focus: string;
  timestamp: string;
}


/**
 * Defines a reference to a line of user code, used to display the context of the feedback
 */
export interface CodeReference {
  lineNum: number;
  code: string;
}